services:
  hashing-service:
    build:
      context: ./hashing
      dockerfile: Dockerfile
    image: hashing-service:latest
    ports:
      - "8001:8001"
    networks:
      - app-network
    volumes:
      - ./hashing/data:/work/app/data
    # user: "${UID}:${GID}"

  frontend:
    build:
      context: ./frontend/dam-app
      dockerfile: Dockerfile
    image: dam-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
