import { AssetCardProps } from "./asset-card";

export const MOCK_ASSETS: AssetCardProps[] = [
    {
        category: "PHOTOGRAPH",
        title: "Sunset Landscape",
        hash: "0xf7a3c19e88d4...1b3c",
        id: 1042,
        date: "Jun 28, 2026",
        status: "minted",
    },
    {
        category: "DIGITAL ART",
        title: "Abstract Composition",
        hash: "0xabc123def456...7890",
        id: 1043,
        date: "Jun 29, 2026",
        status: "flagged",
    },
    {
        category: "LOGO",
        title: "Company Branding",
        hash: "0xdef456ghi789...0123",
        id: 1044,
        date: "Jun 30, 2026",
        status: "minted",
    },
    {
        category: "PHOTOGRAPH",
        title: "Urban Street Scene",
        hash: "0xghi789jkl012...3456",
        id: 1045,
        date: "Jul 1, 2026",
        status: "flagged",
    },
    {
        category: "DIGITAL ART",
        title: "Cyberpunk Character",
        hash: "0xjkl012mno345...6789",
        id: 1046,
        date: "Jul 2, 2026",
        status: "minted",
    },
    {
        category: "LOGO",
        title: "Product Identity",
        hash: "0xno345pqr678...9012",
        id: 1047,
        date: "Jul 3, 2026",
        status: "flagged",
    },
    {
        category: "PHOTOGRAPH",
        title: "Mountain View",
        hash: "0xstu901vwx234...5678",
        id: 1048,
        date: "Jul 4, 2026",
        status: "minted",
    },
    {
        category: "DIGITAL ART",
        title: "Fantasy Creature",
        hash: "0xxyz345abc678...9012",
        id: 1049,
        date: "Jul 5, 2026",
        status: "flagged",
    },
    {
        category: "LOGO",
        title: "Startup Branding",
        hash: "0xdef456ghi789...0123",
        id: 1050,
        date: "Jul 6, 2026",
        status: "minted",
    },
];
